erDiagram

    ROL {
        INT ID_ROL PK
        VARCHAR NOMBRE_ROL
        VARCHAR DESCRIPCION
    }

    USUARIO {
        INT ID_USUARIO PK
        VARCHAR NOMBRE_USUARIO UK
        VARCHAR CONTRASENA
        BOOLEAN ESTADO
        INT ID_ROL FK
    }

    PERIODO_ACADEMICO {
        INT ID_PERIODO PK
        VARCHAR NOMBRE_PERIODO UK
        DATE FECHA_INICIO
        DATE FECHA_FIN
        VARCHAR ESTADO
    }

    CURSO {
        INT ID_CURSO PK
        VARCHAR CODIGO_CURSO UK
        VARCHAR NOMBRE_CURSO
        VARCHAR DESCRIPCION
        INT ID_PERIODO FK
        INT ID_INSTRUCTOR FK
        VARCHAR ESTADO
    }

    MATRICULA {
        INT ID_MATRICULA PK
        INT ID_ESTUDIANTE FK
        INT ID_CURSO FK
        DATE FECHA_MATRICULA
    }

    PAGO {
        INT ID_PAGO PK
        INT ID_ESTUDIANTE FK
        DECIMAL MONTO
        DATE FECHA_PAGO
        VARCHAR RUTA_COMPROBANTE
        VARCHAR ESTADO_PAGO
        INT ID_ASESOR_VALIDADOR FK
    }

    FACTURA {
        INT ID_FACTURA PK
        VARCHAR NUMERO_FACTURA UK
        INT ID_PAGO FK
        INT ID_ESTUDIANTE FK
        DATE FECHA_EMISION
        DECIMAL MONTO_TOTAL
    }

    MATERIAL_DIDACTICO {
        INT ID_MATERIAL PK
        INT ID_CURSO FK
        VARCHAR TITULO_MATERIAL
        VARCHAR RUTA_ARCHIVO
        DATE FECHA_SUBIDA
    }

    ACTIVIDAD_EVALUATIVA {
        INT ID_ACTIVIDAD PK
        INT ID_CURSO FK
        VARCHAR NOMBRE_ACTIVIDAD
        VARCHAR DESCRIPCION
        DATE FECHA_LIMITE
        DECIMAL PONDERACION
    }

    ENTREGA_EVALUACION {
        INT ID_ENTREGA PK
        INT ID_ACTIVIDAD FK
        INT ID_ESTUDIANTE FK
        VARCHAR RUTA_ARCHIVO_ENTREGA
        DATE FECHA_ENTREGA
        DECIMAL CALIFICACION
        VARCHAR OBSERVACIONES
    }

    ROL ||--o{ USUARIO : asigna

    PERIODO_ACADEMICO ||--o{ CURSO : contiene

    USUARIO ||--o{ CURSO : imparte

    USUARIO ||--o{ MATRICULA : realiza
    CURSO ||--o{ MATRICULA : recibe

    USUARIO ||--o{ PAGO : realiza
    USUARIO o|--o{ PAGO : valida

    PAGO ||--o| FACTURA : genera
    USUARIO ||--o{ FACTURA : pertenece

    CURSO ||--o{ MATERIAL_DIDACTICO : contiene

    CURSO ||--o{ ACTIVIDAD_EVALUATIVA : contiene

    ACTIVIDAD_EVALUATIVA ||--o{ ENTREGA_EVALUACION : recibe
    USUARIO ||--o{ ENTREGA_EVALUACION : realiza